name = "KuraBetterVanilla"
author = "Kira"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25b1892599d93c15053e84d02d624c662ca1cc7ebd9c2a3ec632c1767f4e9335"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
