name = "KuraBetterVanilla"
author = "Kira"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a048b5bb4db51d9cd6625933e4b7345900c12604edbb728c633d2d7f02cdee09"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
