name = "KuraBetterVanilla"
author = "Kira"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cf7a43efc3e7ed4f0933345642ca0bc8b713eee6a9fc222e8d83aa728327704"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
