name = "KuraBetterVanilla"
author = "Kira"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63fedaff5c0240f074432c33722126fb4d189c3f30da8afa37d6a30266825355"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
