name = "KuraBetterVanilla"
author = "Kira"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1046b9cd6f9f044e66f7d6f62038c2557e6d64dd4ec7a4f0d06b672f82a0e11"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
